/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.josephmoiselle.jm.dsa.ca1.app;

/**
 *
 * @author Joseph Moiselle 24308453
 */
public class MainGUI extends javax.swing.JFrame {
    
    boolean admin = false;
     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Queue = new javax.swing.JButton();
        ViewByLocation = new javax.swing.JButton();
        ideaSubmission = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        loginstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Queue.setText("Project Queue");
        Queue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueActionPerformed(evt);
            }
        });

        ViewByLocation.setText("View by Location");
        ViewByLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewByLocationActionPerformed(evt);
            }
        });

        ideaSubmission.setText("Submit an idea");
        ideaSubmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ideaSubmissionActionPerformed(evt);
            }
        });

        Login.setText("Log in");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        loginstatus.setText("Logged out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(Exit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ideaSubmission, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Queue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewByLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Queue)
                .addGap(18, 18, 18)
                .addComponent(ViewByLocation)
                .addGap(18, 18, 18)
                .addComponent(ideaSubmission)
                .addGap(38, 38, 38)
                .addComponent(loginstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(Login))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueActionPerformed
        // TODO add your handling code here:
        
        //checks if the user is "logged in" and if so, displays a different page
        if(admin){
        
            ProjectQueueAdminGUI adminQueue = new ProjectQueueAdminGUI();
            adminQueue.setVisible(true);
            
        } else{
            
            ProjectQueueGUI queue = new ProjectQueueGUI();
            queue.setVisible(true);

        }
        
        dispose();
        
    }//GEN-LAST:event_QueueActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        
        // checks if the user is logged in and if so, logs them out, if not logs them in
        if(admin){
        
            admin = false;
            
            
        }else{
            
            admin= true;
            
        }
        
        // updates the text of buttons on the page depending on if the user is logged in or not
        if(admin){
        
            Login.setText("Log out");
            loginstatus.setText("Logged in");
            ideaSubmission.setText("Review submissions");
            
            
        }else{
        
            Login.setText("Log in");
            loginstatus.setText("Logged out");
            ideaSubmission.setText("Submit an idea");
            
            
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void ideaSubmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ideaSubmissionActionPerformed
        // TODO add your handling code here:
        
        //like the projectqueue button, checks if the user is logged in or not and opens a different page depending on login status
        if(admin){
            
            ReviewIdeasGUI reviewideas = new ReviewIdeasGUI();
            reviewideas.setVisible(true);
            dispose();
        
        }else{
        
            SubmitIdeaGUI submission = new SubmitIdeaGUI();
            submission.setVisible(true);
            dispose();
            
        }
    }//GEN-LAST:event_ideaSubmissionActionPerformed

    private void ViewByLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewByLocationActionPerformed
        // TODO add your handling code here:
        ViewProjectsGUI viewprojects = new ViewProjectsGUI();
        viewprojects.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewByLocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Login;
    private javax.swing.JButton Queue;
    private javax.swing.JButton ViewByLocation;
    private javax.swing.JButton ideaSubmission;
    private javax.swing.JLabel loginstatus;
    // End of variables declaration//GEN-END:variables
}
