/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.josephmoiselle.jm.dsa.ca1.app;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph Moiselle 24308453
 */
public class ProjectQueueGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjectQueueGUI.class.getName());
    
    Projects[] project = new Projects[20];

    /**
     * Creates new form ProjectQueueGUI
     */
    public ProjectQueueGUI() {
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QueueDisplay = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();
        Upvote = new javax.swing.JButton();
        UpvoteID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        QueueDisplay.setViewportView(jTextArea1);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Upvote.setText("Upvote");

        jLabel1.setText("ID of Project you wish to upvote:");

        jLabel2.setText("Queue:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QueueDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpvoteID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(Upvote))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Upvote)
                    .addComponent(UpvoteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back)
                    .addComponent(QueueDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MainGUI MainPage = new MainGUI();
        MainPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProjectQueueGUI().setVisible(true));
    }
    
    public void load(){
    
        try{
            
            FileInputStream fis = new FileInputStream("Projects.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            Projects[] file = (Projects[]) ois.readObject();
            ois.close();
            
            for(int i = 0; i <=9; i++){
            
            project[i] = file[i];
            
        }
        
        }catch(FileNotFoundException e){
            
            JOptionPane.showMessageDialog(null, e);
        
        }catch(IOException e){
        
            JOptionPane.showMessageDialog(null, e);
            
        }catch(ClassNotFoundException e){
        
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        String Queue = "1. Title:"+ project[0].title+ "\nDescription: "+project[0].desc+ "\nArea: "+project[0].area+ "\nBudget: "+project[0].budget+ "\nTimeframe:"+project[0].timeframe +
                "\n2. Title:"+ project[1].title+ "\nDescription: "+project[1].desc+ "\nArea: "+project[1].area+ "\nBudget: "+project[1].budget+ "\nTimeframe:"+project[1].timeframe+ 
                "\n3. Title:"+ project[2].title+ "\nDescription: "+project[2].desc+ "\nArea: "+project[2].area+ "\nBudget: "+project[2].budget+ "\nTimeframe:"+project[2].timeframe+ 
                "\n4. Title:"+ project[3].title+ "\nDescription: "+project[3].desc+ "\nArea: "+project[3].area+ "\nBudget: "+project[3].budget+ "\nTimeframe:"+project[3].timeframe+
                "\n5. Title:"+ project[4].title+ "\nDescription: "+project[4].desc+ "\nArea: "+project[4].area+ "\nBudget: "+project[4].budget+ "\nTimeframe:"+project[4].timeframe+
                "\n6. Title:"+ project[5].title+ "\nDescription: "+project[5].desc+ "\nArea: "+project[5].area+ "\nBudget: "+project[5].budget+ "\nTimeframe:"+project[5].timeframe+ 
                "\n7. Title:"+ project[6].title+ "\nDescription: "+project[6].desc+ "\nArea: "+project[6].area+ "\nBudget: "+project[6].budget+ "\nTimeframe:"+project[6].timeframe+ 
                "\n8. Title:"+ project[7].title+ "\nDescription: "+project[7].desc+ "\nArea: "+project[7].area+ "\nBudget: "+project[7].budget+ "\nTimeframe:"+project[7].timeframe+ 
                "\n9. Title:"+ project[8].title+ "\nDescription: "+project[8].desc+ "\nArea: "+project[8].area+ "\nBudget: "+project[8].budget+ "\nTimeframe:"+project[8].timeframe+ 
                "\n10. Title:"+ project[9].title+ "\nDescription: "+project[9].desc+ "\nArea: "+project[9].area+ "\nBudget: "+project[9].budget+ "\nTimeframe:"+project[9].timeframe+ 
                "\n11. Title:"+ project[10].title+ "\nDescription: "+project[10].desc+ "\nArea: "+project[10].area+ "\nBudget: "+project[10].budget+ "\nTimeframe:"+project[10].timeframe+ 
                "\n12. Title:"+ project[11].title+ "\nDescription: "+project[11].desc+ "\nArea: "+project[11].area+ "\nBudget: "+project[11].budget+ "\nTimeframe:"+project[11].timeframe+ 
                "\n13. Title:"+ project[12].title+ "\nDescription: "+project[12].desc+ "\nArea: "+project[12].area+ "\nBudget: "+project[12].budget+ "\nTimeframe:"+project[12].timeframe+ 
                "\n14. Title:"+ project[13].title+ "\nDescription: "+project[13].desc+ "\nArea: "+project[13].area+ "\nBudget: "+project[13].budget+ "\nTimeframe:"+project[13].timeframe+ 
                "\n15. Title:"+ project[14].title+ "\nDescription: "+project[14].desc+ "\nArea: "+project[14].area+ "\nBudget: "+project[14].budget+ "\nTimeframe:"+project[14].timeframe+ 
                "\n16. Title:"+ project[15].title+ "\nDescription: "+project[15].desc+ "\nArea: "+project[15].area+ "\nBudget: "+project[15].budget+ "\nTimeframe:"+project[15].timeframe+ 
                "\n17. Title:"+ project[16].title+ "\nDescription: "+project[16].desc+ "\nArea: "+project[16].area+ "\nBudget: "+project[16].budget+ "\nTimeframe:"+project[16].timeframe+ 
                "\n18. Title:"+ project[17].title+ "\nDescription: "+project[17].desc+ "\nArea: "+project[17].area+ "\nBudget: "+project[17].budget+ "\nTimeframe:"+project[17].timeframe+ 
                "\n19. Title:"+ project[18].title+ "\nDescription: "+project[18].desc+ "\nArea: "+project[18].area+ "\nBudget: "+project[18].budget+ "\nTimeframe:"+project[18].timeframe+ 
                "\n20. Title:"+ project[19].title+ "\nDescription: "+project[19].desc+ "\nArea: "+project[19].area+ "\nBudget: "+project[19].budget+ "\nTimeframe:"+project[19].timeframe;
        
        jTextArea1.setText(Queue);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JScrollPane QueueDisplay;
    private javax.swing.JButton Upvote;
    private javax.swing.JTextField UpvoteID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
